name: materikas
description: "Aplikasi Kasir."
publish_to: "none"
version: 1.0.2

environment:
  sdk: ^3.5.0

dependencies:
  connectivity_plus: ^6.0.5
  collection: ^1.18.0
  esc_pos_utils_plus: ^2.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  material_symbols_icons: ^4.2785.1
  powersync: ^1.5.3
  supabase_flutter: ^2.6.0
  syncfusion_flutter_datepicker: ^27.1.52
  thermal_printer: ^1.0.5
  csv: ^6.0.0
  auto_updater: ^0.2.1
  window_manager: ^0.4.2
  flutter_countdown_timer: ^4.1.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.4
  webview_windows: ^0.4.0
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - .env
