name: materikas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  connectivity_plus: ^6.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.19.0
  material_symbols_icons: ^4.2785.1
  powersync: ^1.5.3
  supabase_flutter: ^2.6.0
  syncfusion_flutter_datepicker: ^26.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
