name: materikas
description: "Aplikasi Kasir."
publish_to: "none"
version: 1.5.4+12

environment:
  sdk: ^3.5.0

dependencies:
  connectivity_plus: ^6.0.5
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  material_symbols_icons: ^4.2785.1
  powersync: ^1.5.3
  syncfusion_flutter_datepicker: ^27.1.52
  thermal_printer: ^1.0.5
  csv: ^6.0.0
  auto_updater: ^0.2.1
  window_manager: ^0.4.2
  flutter_countdown_timer: ^4.1.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.4
  webview_flutter: ^3.0.4
  permission_handler: ^11.3.1
  file_picker: ^8.1.3
  excel: ^4.0.6
  supabase_flutter: ^2.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_inappwebview: ^6.1.5
  file_saver: ^0.2.5
  image_picker: ^1.1.2
  powersync_attachments_helper: ^0.6.16
  device_info_plus: ^11.1.1
  flutter_screenutil: ^5.9.3
  flutter_thermal_printer: ^0.0.20
  shared_preferences: ^2.3.4
  flutter_barcode_scanner: ^2.0.0
  dropdown_search: ^6.0.1
  fl_chart: ^0.69.2
  esc_pos_utils_plus: ^2.0.4
  flutter_pdfview: ^1.4.0
  desktop_webview_window: ^0.2.3
  image: ^4.1.3
  printing: ^5.14.0
  win32: ^5.10.1
  # bitmap: ^0.2.0
  # esc_pos_printer: ^4.1.0
  flutter_esc_pos_utils: ^1.0.1
  directprint: ^1.0.3
  print_usb: ^0.0.3
  ffi: ^2.0.0
  process: ^4.0.1
  share_plus: ^10.1.4
  crop_your_image: ^2.0.0
  # font_awesome_flutter: ^10.8.0
  # opencv_4: ^1.0.0
  pdf: ^3.11.1
  # pdf_render: ^1.4.7
  # flutter_isolate: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
    - assets/logo.png
    - assets/printer/PrintImage.exe
    - assets/template_tambah_barang_materikas.xlsx


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/play_store_512.png"
  adaptive_icon_background: "#FFFFFF"  # Atur background warna (Android)
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"